version: '3.6'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=namdp
      - MONGO_INITDB_ROOT_PASSWORD=123123
    volumes:
      - mongodb:/data/db
      - mongodbconfig:/data/configdb
volumes:
  mongodb:
  mongodbconfig:

